backend:
  name: git-gateway
  branch: dev

media_folder: "public/media/uploads"
public_folder: "media/uploads"

collections:
  - name: combos
    label: Combo Items
    label_singular: "Combo Item"
    description: >
      Below you can update the menu for the Combo Items. To add a new item, just click *New Menu Item* above.

      You can enable and disable existing items by opening them and clicking the "Active" checkbox.
    extension: json
    folder: public/content/_combos
    slug: "{{year}}{{month}}{{day}}{{hour}{{minute}{{second}}-{{slug}}"
    summary: "{{title}}"
    create: true
    delete: true
    fields:
        - { label: "Name", name: name, widget: string }
        - { label: "Description", name: desc, widget: string, required: false }
        - { label: "Price", name: price, widget: number, min: 0 }
        - {
            label: Photo,
            name: thumbnail,
            widget: image,
            allow_multiple: false,
          }

  - name: additionalmenu
    label: Additional Menu Items
    label_singular: Item
    description: >
      Here you can add any menu items which aren't a combo plate!
    folder: public/content/_additionalmenu
    slug: "{{year}}{{month}}{{day}}{{hour}{{minute}{{second}}-{{slug}}"
    summary: "{{title}}"
    create: true
    delete: true
    fields:
        - { label: "Name", name: name, widget: string }
        - { label: "Description", name: desc, widget: string, required: false }
        - { label: "Price", name: price, widget: number, min: 0 }
        - {
            label: Photo,
            name: thumbnail,
            widget: image,
            allow_multiple: false,
          }

  - name: calendar
    label: Calendar
    label_singular: "Event"
    description: >
      Add all upcoming events and locations for the truck here.
    extension: json
    folder: public/content/_calendar
    slug: "{{fields.eventdate}}-{{starttime}}-{{name}}"
    summary: "{{fields.eventdate}} at {{starttime}} - {{name}}"
    create: true
    delete: true
    # TODO: add filter to hide past events
    fields:
      - {
          label: Name,
          name: name,
          widget: string,
          tagname: h1,
          hint: "Examples: *Food truck festival, Company Office Lunch, Creekside*",
        }
      - { label: "Address", name: address, widget: string }
      - {
          label: "Date",
          name: eventdate,
          widget: datetime,
          default: "",
          time_format: false,
          format: "YYYY-MM-DD",
        }
      - {
          label: "Start Time",
          name: starttime,
          widget: datetime,
          default: "",
          date_format: false,
          format: "HH:mm",
        }
      - {
          label: "End Time",
          name: endtime,
          widget: datetime,
          default: "",
          date_format: false,
          format: "HH:mm",
        }
      - {
          label: "Event Description",
          name: body,
          widget: markdown,
          required: false,
        }

    # Below is the current, single-file-based implementation.
  - name: "settings"
    label: "Website Settings"
    extension: json
    files:
      - name: settings
        label: "Settings"
        delete: false
        file: "public/content/settings.json"
        fields:
          - { label: "Section Title", name: title, widget: string }
