backend:
  name: git-gateway
  branch: master

media_folder: "public/media/uploads"
public_folder: "media/uploads"

collections:
  - name: combos
    label: Combo Items
    label_singular: "Combo Item"
    description: >
      Below you can update the menu for the Combo Items. To add a new item, just click *New Menu Item* above.

      You can enable and disable existing items by opening them and clicking the "Active" checkbox.
    extension: json
    folder: public/content/_combos
    slug: "{{year}}{{month}}{{day}}-{{title}}"
    summary: "{{title}}"
    create: true
    delete: true
    fields:
      - {
          label: Active,
          name: active,
          widget: boolean,
          default: true,
          required: false,
        }
      - { label: "Name", name: title, widget: string }
      - { label: "Description", name: desc, widget: string, required: false }
      - { label: "Price", name: price, widget: number, min: 0 }
      - { label: Photo, name: thumbnail, widget: image, allow_multiple: false }

  - name: additionalmenu
    label: Additional Menu Items
    label_singular: Item
    description: >
      Here you can add any menu items which aren't a combo plate!
    extension: json
    folder: public/content/_additionalmenu
    slug: "{{year}}{{month}}{{day}}-{{title}}"
    summary: "{{title}}"
    create: true
    delete: true
    fields:
      - {
          label: Active,
          name: active,
          widget: boolean,
          default: true,
          required: false,
        }
      - { label: "Name", name: title, widget: string }
      - { label: "Description", name: desc, widget: string, required: false }
      - { label: "Price", name: price, widget: number, min: 0 }
      - { label: Photo, name: thumbnail, widget: image, allow_multiple: false }

  - name: calendar
    label: Calendar
    label_singular: "Event"
    description: >
      Add all upcoming events and locations for the truck here.
    extension: json
    folder: public/content/_calendar
    slug: "{{fields.eventdate}}-{{starttime}}-{{name}}"
    summary: "{{fields.eventdate}} at {{starttime}} - {{name}}"
    filter: { field: eventdate, value }
    create: true
    delete: true
    fields:
      - {
          label: Name,
          name: name,
          widget: string,
          tagname: h1,
          hint: "Examples: *Food truck festival, Company Office Lunch, Creekside*",
        }
      - { label: "Address", name: address, widget: string }
      - {
          label: "Date",
          name: eventdate,
          widget: datetime,
          default: "",
          time_format: false,
          format: "YYYY-MM-DD",
        }
      - {
          label: "Start Time",
          name: starttime,
          widget: datetime,
          default: "",
          date_format: false,
          format: "HH:mm",
        }
      - {
          label: "End Time",
          name: endtime,
          widget: datetime,
          default: "",
          date_format: false,
          format: "HH:mm",
        }
      - {
          label: "Event Description",
          name: body,
          widget: markdown,
          required: false,
        }

    # Below is the current, single-file-based implementation.
  - name: "settings"
    label: "Website Settings"
    extension: json
    files:
      - name: settings
        label: "Settings"
        create: false
        delete: false
        file: "public/content/settings.json"
        fields:
          - {
              label: "Site Title",
              name: title,
              widget: string,
              default: "Ono Turo-Turo",
            }
          - {
              label: "Site Subtitle",
              name: subtitle,
              widget: string,
              default: "Hawaiian-Filipino Food Truck",
            }
          - {
              label: "Location",
              name: location,
              widget: string,
              default: "Gahanna, OH",
            }
          - {
              label: "Phone/Contant",
              name: contact,
              widget: string,
              default: "614-403-8051",
              required: false,
            }
      - name: menuSetting
        label: "Menu Settings"
        create: false
        delete: false
        file: "public/content/menusettings.json"
        fields:
          - {
              label: "Combo Items Title",
              name: comboTitle,
              hint: "WARNING: change with caution!",
              widget: string,
              default: "Combo Items",
            }
          - {
              label: "Combo Items Subtitle",
              name: comboSubtitle,
              hint: "WARNING: change with caution!",
              widget: string,
              default: "Comes with macaroni salad and choice of fried rice or rice noodles",
            }
          - {
              label: "Additional Items Title",
              name: additionalTitle,
              hint: "WARNING: change with caution!",
              widget: string,
              default: "Additional Items",
            }
      - name: ourstory
        label: "Our Story"
        create: false
        delete: false
        file: "public/content/ourstory.json"
        fields:
          - {
              label: "Our Story",
              hint: "The story of Ono Turo-Turo. Leave blank to hide from site",
              name: outstory,
              widget: markdown,
            }
