backend:
  name: git-gateway
  branch: dev

# publish_mode: editorial_workflow
media_folder: "public/media/uploads"
public_folder: "media/uploads"

collections:
 -  name: "menu"
    label: "Menu"
    extension: json
    files:
      - name: "menu-items"
        label: "Menu Sections"
        file: "public/content/menu.json"
        create: true
        delete: true
        widget: "list"
        fields: 
          - {label: "Section Title", name: title, widget: string}
          - {label: "Section Subtitle", name: subtitle, widget: string, required: false}
          - name: items
            label: "Items"
            create: true
            delete: true
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Price, name: price, widget: number, min: 0}
              - {label: Photo, name: src, widget: image, allow_multiple: false}
          
